name: Java CI with Maven on Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java: 17
            additional-maven-args: "-Pjacoco coveralls:report"
          - java: 21

    name: Build with Java ${{ matrix.java }} on Linux

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Build with Maven
        run: mvn -f smart-parking/pom.xml clean verify ${{ matrix.additional-maven-args }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      - name: Generate JUnit Report
        run: mvn -f smart-parking/pom.xml surefire-report:report-only
        if: ${{ always() }}
      - name: Archive JUnit Report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: surefire-report-jdk-${{ matrix.java }}
          path: '**/target/reports'